---
local:
  prompt: "[you@laptop:~]$"
  bash_shebang: "#!/usr/bin/env bash"

snippets: Comet_HPC_Intro
baseurl: "https://NewcastleRSE-Training.github.io/probable-pancake/"

remote:
  name: "Introduction to HPC for Comet"
  host_id: #"NCL_Comet"
  login: "cometlogin01.comet.hpc.ncl.ac.uk"
  host: "cometlogin01"
  node: "smnode1"
  location: "cluster.hpc-carpentry.org"
  homedir: "/mnt/nfs/home"
  user: "yourUsername"
  prompt: '[yourUsername@cometlogin01(comet) ~]'
  prompt_work: #"userid@uan01:/work/ta114/ta114/userid>"
  module_python3: "Python"
  bash_shebang: "#!/bin/bash"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: "--account=comet_training --partition=short_free"
  queue:
    debug: "smnode"
    testing: "cpubase_bycore_b1"
  status: "squeue"
  flag:
    user: "-u yourUsername"
    interactive: ""
    histdetail: "-l -j"
    name: "-J"
    time: "-t"
    queue: "-p"
    nodes: ""
    tasks: ""
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct -u yourUsername"
  hist_filter: ""
  partition: "standard"
  reservation: "shortqos"
  qos: "short"
  budget: "short"
  project: ""
main_config: "lesson_config_hpcc.yaml"
